# Generated by Django 4.2.13 on 2024-06-22 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_id', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
